### Numpy Bacis to Advance

1-d array - Vector  
2-d array - matrix  
n-d array - tensor  


Faster than list  
support only one data types

In [2]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


## Create Numpy Array -- 1d

In [4]:
import numpy as np

In [5]:
nums = [55,44,23,54,8,8,451,2]
type(nums)

list

In [6]:
nums= np.array(nums)
print(nums)
type(nums)

[ 55  44  23  54   8   8 451   2]


numpy.ndarray

In [7]:
nums

array([ 55,  44,  23,  54,   8,   8, 451,   2])

## 2D

In [8]:
nums =np.array([[2,6,4,21],[33,4,22,4]])
nums

array([[ 2,  6,  4, 21],
       [33,  4, 22,  4]])

In [9]:
nums.ndim

2

In [10]:
nums.shape

(2, 4)

# 3D

In [11]:
nums =np.array([[
                [2,6,4,21],[33,4,22,4], [42,66,8,0]
              ]])
nums

array([[[ 2,  6,  4, 21],
        [33,  4, 22,  4],
        [42, 66,  8,  0]]])

In [12]:
nums.ndim

3

In [13]:
nums.shape

(1, 3, 4)

In [14]:
nums =np.array([[[2,6,4,21],[33,4,22,4], [42,66,8,0], [2,6,4,21],[33,4,22,4], [42,66,8,0]]])
nums

array([[[ 2,  6,  4, 21],
        [33,  4, 22,  4],
        [42, 66,  8,  0],
        [ 2,  6,  4, 21],
        [33,  4, 22,  4],
        [42, 66,  8,  0]]])

In [15]:
# return dimension 
nums.ndim

3

In [16]:
# return shape
nums.shape

(1, 6, 4)

In [17]:
nums =np.array([[[2,6,4,21],[33,4,22,4], [42,66,8,0]], [[2,6,4,21],[33,4,22,4], [42,66,8,0]]])
nums

array([[[ 2,  6,  4, 21],
        [33,  4, 22,  4],
        [42, 66,  8,  0]],

       [[ 2,  6,  4, 21],
        [33,  4, 22,  4],
        [42, 66,  8,  0]]])

In [18]:
nums.ndim

3

In [19]:
nums.shape

(2, 3, 4)

In [20]:
nums =np.array([[[[2,6,4,21],[33,4,22,4], [42,66,8,0]], [[2,6,4,21],[33,4,22,4], [42,66,8,0]]]])
nums

array([[[[ 2,  6,  4, 21],
         [33,  4, 22,  4],
         [42, 66,  8,  0]],

        [[ 2,  6,  4, 21],
         [33,  4, 22,  4],
         [42, 66,  8,  0]]]])

In [21]:
nums.ndim

4

In [22]:
nums.shape

(1, 2, 3, 4)

In [23]:
nums.dtype

dtype('int32')

# Data type same for every elements of array

In [24]:
nums = np.array(['2',5,'w',6])
nums.dtype

dtype('<U11')

# numpy fuctions
zeros, ones, eye, diag, randint, rand, randn

In [25]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
arr = np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
arr = np.ones(3)
arr

array([1., 1., 1.])

In [28]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
arr = np.diag([3,6,8])  # n-th element n-square matrix
arr

array([[3, 0, 0],
       [0, 6, 0],
       [0, 0, 8]])

In [30]:
np.diag(arr)

array([3, 6, 8])

In [31]:
rand_arr = np.random.randint(1,33,5)  # it will return int value
rand_arr

array([18, 20, 26, 23, 18])

In [32]:
rand_arr = np.random.rand(5)  # return value around 0
rand_arr

array([0.61558352, 0.99907824, 0.14299742, 0.43410914, 0.37522652])

In [33]:
# if u need matrix
rand_arr = np.random.rand(2,2)  # return value around 0 to positive near to 0
rand_arr

array([[0.30795326, 0.23566574],
       [0.27052905, 0.73180873]])

In [34]:
rand_arr.shape

(2, 2)

In [35]:
rand_arr = np.random.randn(2,2)  # return value around 0 including +,-
rand_arr

array([[-0.7734066 , -0.96226096],
       [-1.15299122,  0.05033667]])

In [36]:
np.mean(rand_arr)

-0.7095805274934097

In [37]:
(1.52708358+0.34388637-0.68828395-1.42793214)/4

-0.06131153499999997

# Reshape

In [38]:
arr = np.random.randint(1,50,25)
arr

array([10, 42, 22,  6, 22,  1, 47, 27,  5,  9, 28, 45,  7, 45, 14, 40, 49,
       18, 41, 28, 11, 40, 12,  4, 42])

In [39]:
arr.shape

(25,)

In [40]:
arr.reshape(5,5)

array([[10, 42, 22,  6, 22],
       [ 1, 47, 27,  5,  9],
       [28, 45,  7, 45, 14],
       [40, 49, 18, 41, 28],
       [11, 40, 12,  4, 42]])

In [41]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [43]:
arr.reshape(5,-1)  # -1 automatically detect the comlumn number 

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [44]:
arr.size

10

# Seed

In [45]:
np.random.seed(2)  # just pass any number
arr = np.random.randint(1,50,25)
arr

array([41, 16, 46,  9, 23, 44, 19, 12, 41,  8, 35, 32, 12, 22, 48, 32, 27,
       21, 38, 40,  4, 39,  5, 43, 44])

In [46]:
arr.size

25

# indexing and slicing

In [47]:
arr = np.random.randint(1,50,10)
arr

array([40, 39, 43, 34,  4,  6, 25,  5, 47,  7])

In [48]:
arr[0]

40

In [49]:
arr[:5]

array([40, 39, 43, 34,  4])

In [50]:
arr[-1]

7

In [51]:
arr[-1:-5] # wrong

array([], dtype=int32)

In [52]:
arr[2:5] # slicing

array([43, 34,  4])

In [53]:
arr[1:11:2]

array([39, 34,  6,  5,  7])

# matrix

In [54]:
arr1 = np.random.randint(1,10,3)
arr1

array([4, 3, 1])

In [55]:
arr2 = np.random.randint(1,10,3)
arr2

array([5, 3, 5])

In [56]:
arr3 = np.random.randint(1,10,3)
arr3

array([2, 8, 9])

In [57]:
matrix = np.array([arr1,arr2,arr3])
matrix

array([[4, 3, 1],
       [5, 3, 5],
       [2, 8, 9]])

In [58]:
matrix.ndim

2

In [59]:
matrix.shape

(3, 3)

# indexing

In [60]:
matrix[0][1]

3

In [61]:
matrix[0,1]

3

# slicing

In [62]:
matrix[1:,:2]

array([[5, 3],
       [2, 8]])

# View Vs Copy

In [63]:
arr = np.random.randint(1,50,10)
arr

array([46, 16, 42, 46,  9, 18, 23, 10, 42, 47])

In [64]:
sliced_arr = arr[2:5]
sliced_arr

array([42, 46,  9])

In [65]:
arr[:2]= 0

In [66]:
arr

array([ 0,  0, 42, 46,  9, 18, 23, 10, 42, 47])

In [67]:
sliced_arr[:] = 0
sliced_arr

array([0, 0, 0])

In [68]:
arr     

array([ 0,  0,  0,  0,  0, 18, 23, 10, 42, 47])

# output is not expected :p . because this is just a view/reference.

In [69]:
arr = np.random.randint(1,50,10)
arr
sliced_arr = arr[2:5].copy()
sliced_arr

array([33, 44, 33])

In [70]:
sliced_arr[:] = 0
sliced_arr

array([0, 0, 0])

In [71]:
arr  # no change. it's a copy

array([27, 20, 33, 44, 33, 27,  9, 13, 11, 41])

# conditional selection

In [72]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [74]:
mask = arr>5
mask

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [75]:
arr[mask]

array([ 6,  7,  8,  9, 10])

In [76]:
arr[arr % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [77]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr[arr % 2 == 0] = 0
arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

# Operation on Array with Scaler
Arithmatic operation

In [79]:
arr = np.array([5,65,14,64,5,3,13,4,35])
arr

array([ 5, 65, 14, 64,  5,  3, 13,  4, 35])

In [80]:
arr * 2

array([ 10, 130,  28, 128,  10,   6,  26,   8,  70])

In [81]:
arr + 5

array([10, 70, 19, 69, 10,  8, 18,  9, 40])

In [82]:
arr **4

array([     625, 17850625,    38416, 16777216,      625,       81,
          28561,      256,  1500625], dtype=int32)

# Same with matrix

In [83]:
arr = np.array([5,65,14,64,5,3,13,4,35]).reshape(3,-1)  
arr

array([[ 5, 65, 14],
       [64,  5,  3],
       [13,  4, 35]])

In [84]:
arr + 5

array([[10, 70, 19],
       [69, 10,  8],
       [18,  9, 40]])

In [85]:
arr/ 0      # numpy returns inf

C:\Users\sshuv\AppData\Local\Temp\ipykernel_8748\580118275.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/ 0      # numpy returns inf


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [86]:
# numerical operation on multiple arrays
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(10,20,5)

In [87]:
arr1 + arr2  # shape should be same

array([19, 20, 24, 19, 18])

In [88]:
arr1 * arr2   # it not a proper multiplication system

array([ 48,  91, 108,  84,  77])

In [89]:
arr1 = np.random.randint(1,100,9).reshape(3,3)
arr2 = np.random.randint(100,200,9).reshape(3,3)

In [90]:
arr1.dot(arr2)

array([[34715, 31870, 32581],
       [41006, 39420, 39796],
       [33763, 35217, 34718]])

# numpy functions 

In [91]:
np.min(arr1)

19

In [92]:
np.max(arr1)

98

In [93]:
np.argmin(arr1)  # retunr position/index of min number

6

In [94]:
np.argmax(arr1)  # retunr position/index of max number

5

In [95]:
np.sum(arr1)

618

In [96]:
arr1.sum()

618

In [97]:
arr1

array([[69, 41, 82],
       [62, 71, 98],
       [19, 85, 91]])

In [98]:
arr1.cumsum()   # return sum like fibbonaci # cummulative sum

array([ 69, 110, 192, 254, 325, 423, 442, 527, 618])

In [99]:
np.sqrt(arr1)

array([[8.30662386, 6.40312424, 9.05538514],
       [7.87400787, 8.42614977, 9.89949494],
       [4.35889894, 9.21954446, 9.53939201]])

In [100]:
np.exp(arr1)

array([[9.25378173e+29, 6.39843494e+17, 4.09399696e+35],
       [8.43835667e+26, 6.83767123e+30, 3.63797095e+42],
       [1.78482301e+08, 8.22301271e+36, 3.31740010e+39]])

In [101]:
np.sin(arr1)

array([[-0.11478481, -0.15862267,  0.31322878],
       [-0.7391807 ,  0.95105465, -0.57338187],
       [ 0.14987721, -0.17607562,  0.10598751]])

In [102]:
np.cos(arr1)

array([[ 0.99339038, -0.98733928,  0.9496777 ],
       [ 0.67350716, -0.30902273, -0.81928825],
       [ 0.98870462, -0.98437664, -0.99436746]])

# start, finish, total number linearly spaced 

In [103]:
a = np.linspace(1,15,15) 
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [104]:
a.ndim

1

In [105]:
mat = np.random.randint(20,40,9).reshape(3,3)
mat

array([[20, 36, 31],
       [36, 28, 26],
       [30, 25, 37]])

# axis
axis = 0 means columns axis = 1 means row

In [106]:
np.min(mat, axis=1)

array([20, 26, 25])

In [107]:
np.max(mat, axis=1)

array([36, 36, 37])

In [108]:
np.max(mat, axis=0)

array([36, 36, 37])

In [109]:
np.prod(mat, axis = 1)

array([22320, 26208, 27750])

# shuffle and Unique

In [110]:
mat = np.random.randint(1,20,9)
mat

array([16, 14,  8, 12, 16, 18,  5,  1,  9])

In [111]:
np.random.shuffle(mat)
mat

array([16,  5,  9, 14,  8, 12,  1, 16, 18])

In [112]:
np.unique(mat)

array([ 1,  5,  8,  9, 12, 14, 16, 18])

In [113]:
np.size(mat)

9

In [114]:
np.unique(mat).size

8

In [115]:
np.unique(mat, return_index = True, return_counts= True)

(array([ 1,  5,  8,  9, 12, 14, 16, 18]),
 array([6, 1, 4, 2, 5, 3, 0, 8], dtype=int64),
 array([1, 1, 1, 1, 1, 1, 2, 1], dtype=int64))

 # Horizontal and vertical stacking

In [116]:
arr1 = np.random.randint(1,100,9).reshape(3,3)
arr2 = np.random.randint(1,20,9).reshape(3,3)

In [117]:
arr1

array([[83,  2, 80],
       [92, 97, 50],
       [41, 47, 60]])

In [118]:
arr2

array([[10, 12, 15],
       [15,  1, 17],
       [12,  3, 11]])

In [119]:
np.hstack((arr1,arr2))

array([[83,  2, 80, 10, 12, 15],
       [92, 97, 50, 15,  1, 17],
       [41, 47, 60, 12,  3, 11]])

In [120]:
np.vstack((arr1,arr2))

array([[83,  2, 80],
       [92, 97, 50],
       [41, 47, 60],
       [10, 12, 15],
       [15,  1, 17],
       [12,  3, 11]])

In [121]:
# if we do it with one d array then hstack will return 1d array but vstack will return 2d array

#### Column stack

In [125]:
np.column_stack((arr1,arr2))

array([[83,  2, 80, 10, 12, 15],
       [92, 97, 50, 15,  1, 17],
       [41, 47, 60, 12,  3, 11]])

### Intersection & Difference

In [129]:
import numpy as np
n1 = np.array([10,20,30,40,50,60])
n2 = np.array([50,60,70,80,90])
np.intersect1d(n1,n2)

array([50, 60])

In [130]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [131]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

# EXERCISE : 
1 D TO 3/4D ARRAY

In [ ]:
arr3 = np.random.randint(1,50,24).reshape(2,2,3,2)
arr3

### Create array containing 20 random integer than replace every even number with -1 

In [ ]:
np.random.seed(2)
arr = np.random.randint(1,50,20)
arr[arr % 2 == 0 ] = -1
arr

# Numpy vs Python List

In [ ]:
%timeit 2+3

In [ ]:
%timeit [i**2 for i in range(1,100)]

In [ ]:
%%timeit
l = []
for i in range(1,4):
    l.append(i**2)

In [ ]:
l = []
for i in range(1,4):
    l.append(i**2)
l

In [ ]:
%timeit np.arange(1,100)**2

In [ ]:
arr1=[1,2,4]
arr2=arr1
arr2[0]=0
print(arr1)