### Numpy Bacis to Advance

1-d array - Vector  
2-d array - matrix  
n-d array - tensor  


Faster than list  
support only one data types

In [ ]:
pip install tensorflow

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


## Create Numpy Array -- 1d

In [2]:
import numpy as np

In [3]:
nums = [55,44,23,54,8,8,451,2]
type(nums)

list

In [4]:
nums= np.array(nums)
print(nums)
type(nums)

[ 55  44  23  54   8   8 451   2]


numpy.ndarray

In [5]:
nums

array([ 55,  44,  23,  54,   8,   8, 451,   2])

## 2D

In [6]:
nums =np.array([[2,6,4,21],[33,4,22,4]])
nums

array([[ 2,  6,  4, 21],
       [33,  4, 22,  4]])

In [7]:
nums.ndim

2

In [8]:
nums.shape

(2, 4)

# 3D

In [9]:
nums =np.array([[
                [2,6,4,21],[33,4,22,4], [42,66,8,0]
              ]])
nums

array([[[ 2,  6,  4, 21],
        [33,  4, 22,  4],
        [42, 66,  8,  0]]])

In [10]:
nums.ndim

3

In [11]:
nums.shape

(1, 3, 4)

In [12]:
nums =np.array([[[2,6,4,21],[33,4,22,4], [42,66,8,0], [2,6,4,21],[33,4,22,4], [42,66,8,0]]])
nums

array([[[ 2,  6,  4, 21],
        [33,  4, 22,  4],
        [42, 66,  8,  0],
        [ 2,  6,  4, 21],
        [33,  4, 22,  4],
        [42, 66,  8,  0]]])

In [13]:
# return dimension 
nums.ndim

3

In [14]:
# return shape
nums.shape

(1, 6, 4)

In [15]:
nums =np.array([[[2,6,4,21],[33,4,22,4], [42,66,8,0]], [[2,6,4,21],[33,4,22,4], [42,66,8,0]]])
nums

array([[[ 2,  6,  4, 21],
        [33,  4, 22,  4],
        [42, 66,  8,  0]],

       [[ 2,  6,  4, 21],
        [33,  4, 22,  4],
        [42, 66,  8,  0]]])

In [16]:
nums.ndim

3

In [17]:
nums.shape

(2, 3, 4)

In [18]:
nums =np.array([[[[2,6,4,21],[33,4,22,4], [42,66,8,0]], [[2,6,4,21],[33,4,22,4], [42,66,8,0]]]])
nums

array([[[[ 2,  6,  4, 21],
         [33,  4, 22,  4],
         [42, 66,  8,  0]],

        [[ 2,  6,  4, 21],
         [33,  4, 22,  4],
         [42, 66,  8,  0]]]])

In [19]:
nums.ndim

4

In [20]:
nums.shape

(1, 2, 3, 4)

In [21]:
nums.dtype

dtype('int32')

# Data type same for every elements of array

In [22]:
nums = np.array(['2',5,'w',6])
nums.dtype

dtype('<U11')

# numpy fuctions
zeros, ones, eye, diag, randint, rand, randn

In [23]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
arr = np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
arr = np.ones(3)
arr

array([1., 1., 1.])

In [26]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
arr = np.diag([3,6,8])  # n-th element n-square matrix
arr

array([[3, 0, 0],
       [0, 6, 0],
       [0, 0, 8]])

In [28]:
np.diag(arr)

array([3, 6, 8])

In [29]:
rand_arr = np.random.randint(1,33,5)  # it will return int value
rand_arr

array([ 4, 22,  8, 32, 23])

In [30]:
rand_arr = np.random.rand(5)  # return value around 0
rand_arr

array([0.97624424, 0.9064276 , 0.81431118, 0.65339746, 0.96650834])

In [31]:
# if u need matrix
rand_arr = np.random.rand(2,2)  # return value around 0 to positive near to 0
rand_arr

array([[0.36597898, 0.1419361 ],
       [0.9103215 , 0.34656831]])

In [32]:
rand_arr.shape

(2, 2)

In [33]:
rand_arr = np.random.randn(2,2)  # return value around 0 including +,-
rand_arr

array([[ 1.051736  , -0.81075724],
       [ 0.29021656, -0.74794469]])

In [34]:
np.mean(rand_arr)

-0.054187341387322785

In [35]:
(1.52708358+0.34388637-0.68828395-1.42793214)/4

-0.06131153499999997

# Reshape

In [36]:
arr = np.random.randint(1,50,25)
arr

array([ 1,  5, 48, 29, 25, 30, 45, 35, 31, 40, 35, 39, 41,  4, 29, 35,  4,
       11, 31, 25, 42, 12, 24, 19, 31])

In [37]:
arr.shape

(25,)

In [38]:
arr.reshape(5,5)

array([[ 1,  5, 48, 29, 25],
       [30, 45, 35, 31, 40],
       [35, 39, 41,  4, 29],
       [35,  4, 11, 31, 25],
       [42, 12, 24, 19, 31]])

In [39]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [41]:
arr.reshape(5,-1)  # -1 automatically detect the comlumn number 

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [42]:
arr.size

10

# Seed

In [43]:
np.random.seed(2)  # just pass any number
arr = np.random.randint(1,50,25)
arr

array([41, 16, 46,  9, 23, 44, 19, 12, 41,  8, 35, 32, 12, 22, 48, 32, 27,
       21, 38, 40,  4, 39,  5, 43, 44])

In [44]:
arr.size

25

# indexing and slicing

In [45]:
arr = np.random.randint(1,50,10)
arr

array([40, 39, 43, 34,  4,  6, 25,  5, 47,  7])

In [46]:
arr[0]

40

In [47]:
arr[:5]

array([40, 39, 43, 34,  4])

In [48]:
arr[-1]

7

In [49]:
arr[-1:-5] # wrong

array([], dtype=int32)

In [50]:
arr[2:5] # slicing

array([43, 34,  4])

In [51]:
arr[1:11:2]

array([39, 34,  6,  5,  7])

# matrix

In [52]:
arr1 = np.random.randint(1,10,3)
arr1

array([4, 3, 1])

In [53]:
arr2 = np.random.randint(1,10,3)
arr2

array([5, 3, 5])

In [54]:
arr3 = np.random.randint(1,10,3)
arr3

array([2, 8, 9])

In [55]:
matrix = np.array([arr1,arr2,arr3])
matrix

array([[4, 3, 1],
       [5, 3, 5],
       [2, 8, 9]])

In [56]:
matrix.ndim

2

In [57]:
matrix.shape

(3, 3)

# indexing

In [58]:
matrix[0][1]

3

In [59]:
matrix[0,1]

3

# slicing

In [60]:
matrix[1:,:2]

array([[5, 3],
       [2, 8]])

# View Vs Copy

In [61]:
arr = np.random.randint(1,50,10)
arr

array([46, 16, 42, 46,  9, 18, 23, 10, 42, 47])

In [62]:
sliced_arr = arr[2:5]
sliced_arr

array([42, 46,  9])

In [63]:
arr[:2]= 0

In [64]:
arr

array([ 0,  0, 42, 46,  9, 18, 23, 10, 42, 47])

In [65]:
sliced_arr[:] = 0
sliced_arr

array([0, 0, 0])

In [66]:
arr     

array([ 0,  0,  0,  0,  0, 18, 23, 10, 42, 47])

# output is not expected :p . because this is just a view/reference.

In [67]:
arr = np.random.randint(1,50,10)
arr
sliced_arr = arr[2:5].copy()
sliced_arr

array([33, 44, 33])

In [68]:
sliced_arr[:] = 0
sliced_arr

array([0, 0, 0])

In [69]:
arr  # no change. it's copy

array([27, 20, 33, 44, 33, 27,  9, 13, 11, 41])

# conditional selection

In [70]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [72]:
mask = arr>5
mask

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [73]:
arr[mask]

array([ 6,  7,  8,  9, 10])

In [74]:
arr[arr % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [75]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
arr[arr % 2 == 0] = 0
arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

# Operation on Array with Scaler
Arithmatic operation

In [77]:
arr = np.array([5,65,14,64,5,3,13,4,35])
arr

array([ 5, 65, 14, 64,  5,  3, 13,  4, 35])

In [78]:
arr * 2

array([ 10, 130,  28, 128,  10,   6,  26,   8,  70])

In [79]:
arr + 5

array([10, 70, 19, 69, 10,  8, 18,  9, 40])

In [80]:
arr **4

array([     625, 17850625,    38416, 16777216,      625,       81,
          28561,      256,  1500625], dtype=int32)

# Same with matrix

In [81]:
arr = np.array([5,65,14,64,5,3,13,4,35]).reshape(3,-1)  
arr

array([[ 5, 65, 14],
       [64,  5,  3],
       [13,  4, 35]])

In [82]:
arr + 5

array([[10, 70, 19],
       [69, 10,  8],
       [18,  9, 40]])

In [84]:
arr/ 0      # numpy returns inf

C:\Users\sshuv\AppData\Local\Temp\ipykernel_4540\580118275.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/ 0      # numpy returns inf


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [88]:
# numerical operation on multiple arrays
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(10,20,5)

In [90]:
arr1 + arr2  # shape should be same

array([16, 21, 16, 24, 22])

In [92]:
arr1 * arr2   # it not a proper multiplication system

array([ 55, 108,  28, 119,  96])

In [114]:
arr1 = np.random.randint(1,100,9).reshape(3,3)
arr2 = np.random.randint(100,200,9).reshape(3,3)

In [115]:
arr1.dot(arr2)

array([[19555, 19714, 24562],
       [16776, 16719, 20096],
       [18487, 18859, 23944]])

# numpy functions 

In [116]:
np.min(arr1)

20

In [117]:
np.max(arr1)

96

In [118]:
np.argmin(arr1)  # retunr position/index of min number

7

In [119]:
np.argmax(arr1)  # retunr position/index of max number

8

In [122]:
np.sum(arr1)

416

In [127]:
arr1.sum()

416

In [138]:
arr1

array([[32, 35, 81],
       [43, 49, 37],
       [23, 20, 96]])

In [139]:
arr1.cumsum()   # return sum like fibbonaci # cummulative sum

array([ 32,  67, 148, 191, 240, 277, 300, 320, 416])

In [123]:
np.sqrt(arr1)

array([[5.65685425, 5.91607978, 9.        ],
       [6.55743852, 7.        , 6.08276253],
       [4.79583152, 4.47213595, 9.79795897]])

In [124]:
np.exp(arr1)

array([[7.89629602e+13, 1.58601345e+15, 1.50609731e+35],
       [4.72783947e+18, 1.90734657e+21, 1.17191424e+16],
       [9.74480345e+09, 4.85165195e+08, 4.92345829e+41]])

In [125]:
np.sin(arr1)

array([[ 0.55142668, -0.42818267, -0.62988799],
       [-0.83177474, -0.95375265, -0.64353813],
       [-0.8462204 ,  0.91294525,  0.98358775]])

In [126]:
np.cos(arr1)

array([[ 0.83422336, -0.90369221,  0.77668598],
       [ 0.5551133 ,  0.30059254,  0.76541405],
       [-0.53283302,  0.40808206, -0.18043045]])

# start, finish, total number linearly spaced 

In [129]:
a = np.linspace(1,15,15) 
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [130]:
a.ndim

1

In [132]:
mat = np.random.randint(20,40,9).reshape(3,3)
mat

array([[23, 35, 22],
       [25, 25, 38],
       [25, 32, 26]])

# axis
axis = 0 means columns axis = 1 means row

In [134]:
np.min(mat, axis=1)

array([22, 25, 25])

In [135]:
np.max(mat, axis=1)

array([35, 38, 32])

In [136]:
np.max(mat, axis=0)

array([25, 35, 38])

In [140]:
np.prod(mat, axis = 1)

array([17710, 23750, 20800])

# shuffle and Unique

In [141]:
mat = np.random.randint(1,20,9)
mat

array([18, 13,  6, 17,  6,  8,  6,  5, 16])

In [142]:
np.random.shuffle(mat)
mat

array([ 5,  6, 17, 13, 18, 16,  6,  6,  8])

In [144]:
np.unique(mat)

array([ 5,  6,  8, 13, 16, 17, 18])

In [145]:
np.size(mat)

9

In [146]:
np.unique(mat).size

7

In [147]:
np.unique(mat, return_index = True, return_counts= True)

(array([ 5,  6,  8, 13, 16, 17, 18]),
 array([0, 1, 8, 3, 5, 2, 4], dtype=int64),
 array([1, 3, 1, 1, 1, 1, 1], dtype=int64))

 # Horizontal and vertical stacking

In [148]:
arr1 = np.random.randint(1,100,9).reshape(3,3)
arr2 = np.random.randint(1,20,9).reshape(3,3)

In [149]:
arr1

array([[72, 97, 83],
       [94, 80, 29],
       [21, 91, 81]])

In [150]:
arr2

array([[ 7,  7,  7],
       [12, 18, 10],
       [ 5, 10,  9]])

In [151]:
np.hstack((arr1,arr2))

array([[72, 97, 83,  7,  7,  7],
       [94, 80, 29, 12, 18, 10],
       [21, 91, 81,  5, 10,  9]])

In [152]:
np.vstack((arr1,arr2))

array([[72, 97, 83],
       [94, 80, 29],
       [21, 91, 81],
       [ 7,  7,  7],
       [12, 18, 10],
       [ 5, 10,  9]])

In [153]:
# if we do it with one d array then hstack will return 1d array but vstack will return 2d array

# EXERCISE : 
1 D TO 3/4D ARRAY

In [157]:
arr3 = np.random.randint(1,50,24).reshape(2,2,3,2)
arr3

array([[[[20, 46],
         [45,  3],
         [32, 36]],

        [[27, 11],
         [28, 43],
         [44, 36]]],


       [[[43,  4],
         [30,  1],
         [45,  6]],

        [[11, 12],
         [31, 43],
         [18, 19]]]])

### Create array containing 20 random integer than replace every even number with -1 

In [161]:
np.random.seed(2)
arr = np.random.randint(1,50,20)
arr[arr % 2 == 0 ] = -1
arr

array([41, -1, -1,  9, 23, -1, 19, -1, 41, -1, 35, -1, -1, -1, -1, -1, 27,
       21, -1, -1])

# Numpy vs Python List

In [162]:
%timeit 2+3

11.8 ns ± 0.284 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [172]:
%timeit [i**2 for i in range(1,100)]

29.5 µs ± 1.13 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [167]:
%%timeit
l = []
for i in range(1,4):
    l.append(i**2)

1.2 µs ± 12.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [170]:
l = []
for i in range(1,4):
    l.append(i**2)
l

[1, 4, 9]

In [173]:
%timeit np.arange(1,100)**2

1.72 µs ± 52.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
